{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ancora.fullname" . }}-control-plane
  labels:
    {{- include "ancora.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ancora.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: control-plane
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "ancora.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: worker
      ports:
        - port: {{ .Values.controlPlane.service.port }}
          protocol: TCP
    {{- if .Values.ingress.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: {{ .Values.controlPlane.service.port }}
          protocol: TCP
    {{- end }}
  egress:
    - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ancora.fullname" . }}-worker
  labels:
    {{- include "ancora.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ancora.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "ancora.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: control-plane
      ports:
        - port: {{ .Values.controlPlane.service.port }}
          protocol: TCP
    - {}
{{- end }}
