// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: contracts.proto

package ancora

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Classifies the observable side effect a tool may produce.
type EffectClass int32

const (
	EffectClass_EFFECT_UNSPECIFIED EffectClass = 0
	// No observable side effects; safe to retry or replay at any time.
	EffectClass_EFFECT_PURE EffectClass = 1
	// Reads external state without modifying it.
	EffectClass_EFFECT_READ EffectClass = 2
	// Modifies external state; requires idempotency key for safe replay.
	EffectClass_EFFECT_WRITE EffectClass = 3
)

// Enum value maps for EffectClass.
var (
	EffectClass_name = map[int32]string{
		0: "EFFECT_UNSPECIFIED",
		1: "EFFECT_PURE",
		2: "EFFECT_READ",
		3: "EFFECT_WRITE",
	}
	EffectClass_value = map[string]int32{
		"EFFECT_UNSPECIFIED": 0,
		"EFFECT_PURE":        1,
		"EFFECT_READ":        2,
		"EFFECT_WRITE":       3,
	}
)

func (x EffectClass) Enum() *EffectClass {
	p := new(EffectClass)
	*p = x
	return p
}

func (x EffectClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectClass) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_enumTypes[0].Descriptor()
}

func (EffectClass) Type() protoreflect.EnumType {
	return &file_contracts_proto_enumTypes[0]
}

func (x EffectClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectClass.Descriptor instead.
func (EffectClass) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_rawDescGZIP(), []int{0}
}

// Describes a single tool that an agent may invoke.
type ToolSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable machine-readable identifier.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable description shown to the model.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema (serialized as a JSON string) for the input arguments.
	InputSchemaJson string `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	// JSON Schema (serialized as a JSON string) for the output value.
	OutputSchemaJson string `protobuf:"bytes,4,opt,name=output_schema_json,json=outputSchemaJson,proto3" json:"output_schema_json,omitempty"`
	// Observable side-effect class of this tool.
	EffectClass EffectClass `protobuf:"varint,5,opt,name=effect_class,json=effectClass,proto3,enum=ancora.EffectClass" json:"effect_class,omitempty"`
	// For EFFECT_WRITE tools: a client-supplied idempotency key template.
	// Supports simple variable substitution: {run_id}, {node_id}, {seq}.
	// Empty for non-write tools.
	IdempotencyKeyTemplate string `protobuf:"bytes,6,opt,name=idempotency_key_template,json=idempotencyKeyTemplate,proto3" json:"idempotency_key_template,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolSpec) Reset() {
	*x = ToolSpec{}
	mi := &file_contracts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSpec) ProtoMessage() {}

func (x *ToolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSpec.ProtoReflect.Descriptor instead.
func (*ToolSpec) Descriptor() ([]byte, []int) {
	return file_contracts_proto_rawDescGZIP(), []int{0}
}

func (x *ToolSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSpec) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

func (x *ToolSpec) GetOutputSchemaJson() string {
	if x != nil {
		return x.OutputSchemaJson
	}
	return ""
}

func (x *ToolSpec) GetEffectClass() EffectClass {
	if x != nil {
		return x.EffectClass
	}
	return EffectClass_EFFECT_UNSPECIFIED
}

func (x *ToolSpec) GetIdempotencyKeyTemplate() string {
	if x != nil {
		return x.IdempotencyKeyTemplate
	}
	return ""
}

// Retry policy attached to a model call or tool call.
type RetryPolicy struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts uint32                 `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// Initial backoff in milliseconds.
	InitialBackoffMs uint32 `protobuf:"varint,2,opt,name=initial_backoff_ms,json=initialBackoffMs,proto3" json:"initial_backoff_ms,omitempty"`
	// Maximum backoff in milliseconds.
	MaxBackoffMs uint32 `protobuf:"varint,3,opt,name=max_backoff_ms,json=maxBackoffMs,proto3" json:"max_backoff_ms,omitempty"`
	// Jitter fraction in [0, 1]. 0 means no jitter.
	Jitter        float32 `protobuf:"fixed32,4,opt,name=jitter,proto3" json:"jitter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_contracts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_contracts_proto_rawDescGZIP(), []int{1}
}

func (x *RetryPolicy) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryPolicy) GetInitialBackoffMs() uint32 {
	if x != nil {
		return x.InitialBackoffMs
	}
	return 0
}

func (x *RetryPolicy) GetMaxBackoffMs() uint32 {
	if x != nil {
		return x.MaxBackoffMs
	}
	return 0
}

func (x *RetryPolicy) GetJitter() float32 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

// Specifies a single agent in the graph.
type AgentSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable machine-readable identifier.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Model identifier (e.g. "llama3", "gpt-4o").
	ModelId string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// System prompt / instructions sent before the conversation.
	Instructions string `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	// JSON Schema (serialized as a JSON string) for the structured output.
	// Empty means free-form text output.
	OutputSchemaJson string `protobuf:"bytes,4,opt,name=output_schema_json,json=outputSchemaJson,proto3" json:"output_schema_json,omitempty"`
	// Tools available to this agent.
	Tools []*ToolSpec `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	// Maximum number of reason-act loop iterations before forced termination.
	MaxSteps uint32 `protobuf:"varint,6,opt,name=max_steps,json=maxSteps,proto3" json:"max_steps,omitempty"`
	// Retry policy for the model call.
	ModelRetry *RetryPolicy `protobuf:"bytes,7,opt,name=model_retry,json=modelRetry,proto3" json:"model_retry,omitempty"`
	// Additional model parameters as a JSON object (temperature, top_p, etc.).
	ModelParamsJson string `protobuf:"bytes,8,opt,name=model_params_json,json=modelParamsJson,proto3" json:"model_params_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentSpec) Reset() {
	*x = AgentSpec{}
	mi := &file_contracts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSpec) ProtoMessage() {}

func (x *AgentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSpec.ProtoReflect.Descriptor instead.
func (*AgentSpec) Descriptor() ([]byte, []int) {
	return file_contracts_proto_rawDescGZIP(), []int{2}
}

func (x *AgentSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentSpec) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *AgentSpec) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *AgentSpec) GetOutputSchemaJson() string {
	if x != nil {
		return x.OutputSchemaJson
	}
	return ""
}

func (x *AgentSpec) GetTools() []*ToolSpec {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *AgentSpec) GetMaxSteps() uint32 {
	if x != nil {
		return x.MaxSteps
	}
	return 0
}

func (x *AgentSpec) GetModelRetry() *RetryPolicy {
	if x != nil {
		return x.ModelRetry
	}
	return nil
}

func (x *AgentSpec) GetModelParamsJson() string {
	if x != nil {
		return x.ModelParamsJson
	}
	return ""
}

var File_contracts_proto protoreflect.FileDescriptor

const file_contracts_proto_rawDesc = "" +
	"\n" +
	"\x0fcontracts.proto\x12\x06ancora\"\x8c\x02\n" +
	"\bToolSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\tR\x0finputSchemaJson\x12,\n" +
	"\x12output_schema_json\x18\x04 \x01(\tR\x10outputSchemaJson\x126\n" +
	"\feffect_class\x18\x05 \x01(\x0e2\x13.ancora.EffectClassR\veffectClass\x128\n" +
	"\x18idempotency_key_template\x18\x06 \x01(\tR\x16idempotencyKeyTemplate\"\x9c\x01\n" +
	"\vRetryPolicy\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\rR\vmaxAttempts\x12,\n" +
	"\x12initial_backoff_ms\x18\x02 \x01(\rR\x10initialBackoffMs\x12$\n" +
	"\x0emax_backoff_ms\x18\x03 \x01(\rR\fmaxBackoffMs\x12\x16\n" +
	"\x06jitter\x18\x04 \x01(\x02R\x06jitter\"\xb3\x02\n" +
	"\tAgentSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\"\n" +
	"\finstructions\x18\x03 \x01(\tR\finstructions\x12,\n" +
	"\x12output_schema_json\x18\x04 \x01(\tR\x10outputSchemaJson\x12&\n" +
	"\x05tools\x18\x05 \x03(\v2\x10.ancora.ToolSpecR\x05tools\x12\x1b\n" +
	"\tmax_steps\x18\x06 \x01(\rR\bmaxSteps\x124\n" +
	"\vmodel_retry\x18\a \x01(\v2\x13.ancora.RetryPolicyR\n" +
	"modelRetry\x12*\n" +
	"\x11model_params_json\x18\b \x01(\tR\x0fmodelParamsJson*Y\n" +
	"\vEffectClass\x12\x16\n" +
	"\x12EFFECT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vEFFECT_PURE\x10\x01\x12\x0f\n" +
	"\vEFFECT_READ\x10\x02\x12\x10\n" +
	"\fEFFECT_WRITE\x10\x03BI\n" +
	"\n" +
	"dev.ancoraB\vContractsPbZ.github.com/YASSERRMD/Ancora/bindings/go/ancorab\x06proto3"

var (
	file_contracts_proto_rawDescOnce sync.Once
	file_contracts_proto_rawDescData []byte
)

func file_contracts_proto_rawDescGZIP() []byte {
	file_contracts_proto_rawDescOnce.Do(func() {
		file_contracts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_proto_rawDesc), len(file_contracts_proto_rawDesc)))
	})
	return file_contracts_proto_rawDescData
}

var file_contracts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contracts_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_contracts_proto_goTypes = []any{
	(EffectClass)(0),    // 0: ancora.EffectClass
	(*ToolSpec)(nil),    // 1: ancora.ToolSpec
	(*RetryPolicy)(nil), // 2: ancora.RetryPolicy
	(*AgentSpec)(nil),   // 3: ancora.AgentSpec
}
var file_contracts_proto_depIdxs = []int32{
	0, // 0: ancora.ToolSpec.effect_class:type_name -> ancora.EffectClass
	1, // 1: ancora.AgentSpec.tools:type_name -> ancora.ToolSpec
	2, // 2: ancora.AgentSpec.model_retry:type_name -> ancora.RetryPolicy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_contracts_proto_init() }
func file_contracts_proto_init() {
	if File_contracts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_rawDesc), len(file_contracts_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_proto_goTypes,
		DependencyIndexes: file_contracts_proto_depIdxs,
		EnumInfos:         file_contracts_proto_enumTypes,
		MessageInfos:      file_contracts_proto_msgTypes,
	}.Build()
	File_contracts_proto = out.File
	file_contracts_proto_goTypes = nil
	file_contracts_proto_depIdxs = nil
}
