// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: errors.proto

package ancora

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Canonical error codes for the Ancora wire protocol.
// Values are stable across releases; new codes are only ever added.
type ErrorCode int32

const (
	// Default, should never appear in a real error.
	ErrorCode_ERROR_UNSPECIFIED ErrorCode = 0
	// ---- Replay and determinism ----
	// The code path produced a different event type than the journal records.
	ErrorCode_ERROR_NONDETERMINISM ErrorCode = 1
	// The journal is missing an expected event.
	ErrorCode_ERROR_JOURNAL_GAP ErrorCode = 2
	// The journal store refused a write (e.g. duplicate idempotency key).
	ErrorCode_ERROR_JOURNAL_WRITE ErrorCode = 3
	// ---- Agent loop ----
	// The agent reached its max_steps limit without producing a final output.
	ErrorCode_ERROR_MAX_STEPS ErrorCode = 10
	// The structured output failed schema validation and repair was exhausted.
	ErrorCode_ERROR_OUTPUT_VALIDATION ErrorCode = 11
	// An activity timed out.
	ErrorCode_ERROR_TIMEOUT ErrorCode = 12
	// ---- Inference ----
	// The model refused to produce a response (content policy, etc).
	ErrorCode_ERROR_MODEL_REFUSED ErrorCode = 20
	// The model endpoint returned an HTTP error.
	ErrorCode_ERROR_MODEL_HTTP ErrorCode = 21
	// The model response could not be parsed.
	ErrorCode_ERROR_MODEL_PARSE ErrorCode = 22
	// The model endpoint is not reachable (network error).
	ErrorCode_ERROR_MODEL_UNREACHABLE ErrorCode = 23
	// ---- Tools ----
	// The tool returned an error result.
	ErrorCode_ERROR_TOOL_FAILED ErrorCode = 30
	// The tool is not registered.
	ErrorCode_ERROR_TOOL_NOT_FOUND ErrorCode = 31
	// The tool input failed schema validation.
	ErrorCode_ERROR_TOOL_INPUT_INVALID ErrorCode = 32
	// The tool call was denied by the permission broker.
	ErrorCode_ERROR_TOOL_DENIED ErrorCode = 33
	// ---- Policy ----
	// A call to a disallowed endpoint was blocked by the residency policy.
	ErrorCode_ERROR_POLICY_RESIDENCY ErrorCode = 40
	// A required permission was not granted.
	ErrorCode_ERROR_POLICY_PERMISSION ErrorCode = 41
	// ---- Graph ----
	// The graph definition is malformed.
	ErrorCode_ERROR_GRAPH_INVALID ErrorCode = 50
	// A required node was not found.
	ErrorCode_ERROR_NODE_NOT_FOUND ErrorCode = 51
	// ---- Run lifecycle ----
	// The run was cancelled.
	ErrorCode_ERROR_CANCELLED ErrorCode = 60
	// The run was already in a terminal state.
	ErrorCode_ERROR_INVALID_STATE ErrorCode = 61
	// ---- Storage ----
	// A storage operation failed.
	ErrorCode_ERROR_STORAGE ErrorCode = 70
	// ---- Internal ----
	// An unexpected internal error.
	ErrorCode_ERROR_INTERNAL ErrorCode = 99
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_UNSPECIFIED",
		1:  "ERROR_NONDETERMINISM",
		2:  "ERROR_JOURNAL_GAP",
		3:  "ERROR_JOURNAL_WRITE",
		10: "ERROR_MAX_STEPS",
		11: "ERROR_OUTPUT_VALIDATION",
		12: "ERROR_TIMEOUT",
		20: "ERROR_MODEL_REFUSED",
		21: "ERROR_MODEL_HTTP",
		22: "ERROR_MODEL_PARSE",
		23: "ERROR_MODEL_UNREACHABLE",
		30: "ERROR_TOOL_FAILED",
		31: "ERROR_TOOL_NOT_FOUND",
		32: "ERROR_TOOL_INPUT_INVALID",
		33: "ERROR_TOOL_DENIED",
		40: "ERROR_POLICY_RESIDENCY",
		41: "ERROR_POLICY_PERMISSION",
		50: "ERROR_GRAPH_INVALID",
		51: "ERROR_NODE_NOT_FOUND",
		60: "ERROR_CANCELLED",
		61: "ERROR_INVALID_STATE",
		70: "ERROR_STORAGE",
		99: "ERROR_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_UNSPECIFIED":        0,
		"ERROR_NONDETERMINISM":     1,
		"ERROR_JOURNAL_GAP":        2,
		"ERROR_JOURNAL_WRITE":      3,
		"ERROR_MAX_STEPS":          10,
		"ERROR_OUTPUT_VALIDATION":  11,
		"ERROR_TIMEOUT":            12,
		"ERROR_MODEL_REFUSED":      20,
		"ERROR_MODEL_HTTP":         21,
		"ERROR_MODEL_PARSE":        22,
		"ERROR_MODEL_UNREACHABLE":  23,
		"ERROR_TOOL_FAILED":        30,
		"ERROR_TOOL_NOT_FOUND":     31,
		"ERROR_TOOL_INPUT_INVALID": 32,
		"ERROR_TOOL_DENIED":        33,
		"ERROR_POLICY_RESIDENCY":   40,
		"ERROR_POLICY_PERMISSION":  41,
		"ERROR_GRAPH_INVALID":      50,
		"ERROR_NODE_NOT_FOUND":     51,
		"ERROR_CANCELLED":          60,
		"ERROR_INVALID_STATE":      61,
		"ERROR_STORAGE":            70,
		"ERROR_INTERNAL":           99,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\x06ancora*\xbb\x04\n" +
	"\tErrorCode\x12\x15\n" +
	"\x11ERROR_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ERROR_NONDETERMINISM\x10\x01\x12\x15\n" +
	"\x11ERROR_JOURNAL_GAP\x10\x02\x12\x17\n" +
	"\x13ERROR_JOURNAL_WRITE\x10\x03\x12\x13\n" +
	"\x0fERROR_MAX_STEPS\x10\n" +
	"\x12\x1b\n" +
	"\x17ERROR_OUTPUT_VALIDATION\x10\v\x12\x11\n" +
	"\rERROR_TIMEOUT\x10\f\x12\x17\n" +
	"\x13ERROR_MODEL_REFUSED\x10\x14\x12\x14\n" +
	"\x10ERROR_MODEL_HTTP\x10\x15\x12\x15\n" +
	"\x11ERROR_MODEL_PARSE\x10\x16\x12\x1b\n" +
	"\x17ERROR_MODEL_UNREACHABLE\x10\x17\x12\x15\n" +
	"\x11ERROR_TOOL_FAILED\x10\x1e\x12\x18\n" +
	"\x14ERROR_TOOL_NOT_FOUND\x10\x1f\x12\x1c\n" +
	"\x18ERROR_TOOL_INPUT_INVALID\x10 \x12\x15\n" +
	"\x11ERROR_TOOL_DENIED\x10!\x12\x1a\n" +
	"\x16ERROR_POLICY_RESIDENCY\x10(\x12\x1b\n" +
	"\x17ERROR_POLICY_PERMISSION\x10)\x12\x17\n" +
	"\x13ERROR_GRAPH_INVALID\x102\x12\x18\n" +
	"\x14ERROR_NODE_NOT_FOUND\x103\x12\x13\n" +
	"\x0fERROR_CANCELLED\x10<\x12\x17\n" +
	"\x13ERROR_INVALID_STATE\x10=\x12\x11\n" +
	"\rERROR_STORAGE\x10F\x12\x12\n" +
	"\x0eERROR_INTERNAL\x10cBF\n" +
	"\n" +
	"dev.ancoraB\bErrorsPbZ.github.com/YASSERRMD/Ancora/bindings/go/ancorab\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_goTypes = []any{
	(ErrorCode)(0), // 0: ancora.ErrorCode
}
var file_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
