// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: journal.proto

package ancora

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A run was started.
type RunStartedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Serialized AgentSpec or GraphSpec bytes (proto-encoded).
	SpecBytes     []byte `protobuf:"bytes,2,opt,name=spec_bytes,json=specBytes,proto3" json:"spec_bytes,omitempty"`
	SpecType      string `protobuf:"bytes,3,opt,name=spec_type,json=specType,proto3" json:"spec_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStartedEvent) Reset() {
	*x = RunStartedEvent{}
	mi := &file_journal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStartedEvent) ProtoMessage() {}

func (x *RunStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStartedEvent.ProtoReflect.Descriptor instead.
func (*RunStartedEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{0}
}

func (x *RunStartedEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunStartedEvent) GetSpecBytes() []byte {
	if x != nil {
		return x.SpecBytes
	}
	return nil
}

func (x *RunStartedEvent) GetSpecType() string {
	if x != nil {
		return x.SpecType
	}
	return ""
}

// Execution entered a graph node.
type NodeEnteredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeKind      string                 `protobuf:"bytes,2,opt,name=node_kind,json=nodeKind,proto3" json:"node_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEnteredEvent) Reset() {
	*x = NodeEnteredEvent{}
	mi := &file_journal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEnteredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEnteredEvent) ProtoMessage() {}

func (x *NodeEnteredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEnteredEvent.ProtoReflect.Descriptor instead.
func (*NodeEnteredEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{1}
}

func (x *NodeEnteredEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeEnteredEvent) GetNodeKind() string {
	if x != nil {
		return x.NodeKind
	}
	return ""
}

// Execution exited a graph node.
type NodeExitedEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// true if the node completed without error
	Success       bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeExitedEvent) Reset() {
	*x = NodeExitedEvent{}
	mi := &file_journal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeExitedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeExitedEvent) ProtoMessage() {}

func (x *NodeExitedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeExitedEvent.ProtoReflect.Descriptor instead.
func (*NodeExitedEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{2}
}

func (x *NodeExitedEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeExitedEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// A non-deterministic activity was executed and its result recorded.
type ActivityRecordedEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ActivityKey  string                 `protobuf:"bytes,1,opt,name=activity_key,json=activityKey,proto3" json:"activity_key,omitempty"`
	ActivityKind string                 `protobuf:"bytes,2,opt,name=activity_kind,json=activityKind,proto3" json:"activity_kind,omitempty"`
	// JSON-encoded input sent to the activity.
	InputJson string `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	// JSON-encoded result returned by the activity.
	ResultJson string `protobuf:"bytes,4,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// True on replay: this field being true means the payload was read
	// from a prior journal entry rather than re-executed.
	Replayed      bool `protobuf:"varint,5,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityRecordedEvent) Reset() {
	*x = ActivityRecordedEvent{}
	mi := &file_journal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityRecordedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityRecordedEvent) ProtoMessage() {}

func (x *ActivityRecordedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityRecordedEvent.ProtoReflect.Descriptor instead.
func (*ActivityRecordedEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityRecordedEvent) GetActivityKey() string {
	if x != nil {
		return x.ActivityKey
	}
	return ""
}

func (x *ActivityRecordedEvent) GetActivityKind() string {
	if x != nil {
		return x.ActivityKind
	}
	return ""
}

func (x *ActivityRecordedEvent) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ActivityRecordedEvent) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ActivityRecordedEvent) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

// The run is suspended, awaiting a human decision.
type HumanDecisionRequestedEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Prompt string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Options the human may select. Empty means free-form input.
	Options []string `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	// Deadline in Unix epoch nanoseconds. 0 means no deadline.
	TimeoutAtNs   int64 `protobuf:"varint,3,opt,name=timeout_at_ns,json=timeoutAtNs,proto3" json:"timeout_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanDecisionRequestedEvent) Reset() {
	*x = HumanDecisionRequestedEvent{}
	mi := &file_journal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanDecisionRequestedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanDecisionRequestedEvent) ProtoMessage() {}

func (x *HumanDecisionRequestedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanDecisionRequestedEvent.ProtoReflect.Descriptor instead.
func (*HumanDecisionRequestedEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{4}
}

func (x *HumanDecisionRequestedEvent) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *HumanDecisionRequestedEvent) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *HumanDecisionRequestedEvent) GetTimeoutAtNs() int64 {
	if x != nil {
		return x.TimeoutAtNs
	}
	return 0
}

// A human provided a decision that resumes the run.
type HumanDecisionReceivedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanDecisionReceivedEvent) Reset() {
	*x = HumanDecisionReceivedEvent{}
	mi := &file_journal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanDecisionReceivedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanDecisionReceivedEvent) ProtoMessage() {}

func (x *HumanDecisionReceivedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanDecisionReceivedEvent.ProtoReflect.Descriptor instead.
func (*HumanDecisionReceivedEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{5}
}

func (x *HumanDecisionReceivedEvent) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

// The run completed successfully.
type RunCompletedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded final output.
	OutputJson    string `protobuf:"bytes,1,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCompletedEvent) Reset() {
	*x = RunCompletedEvent{}
	mi := &file_journal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCompletedEvent) ProtoMessage() {}

func (x *RunCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCompletedEvent.ProtoReflect.Descriptor instead.
func (*RunCompletedEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{6}
}

func (x *RunCompletedEvent) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

// An error occurred.
type ErrorEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Serialized stack/context for debugging; not part of replay logic.
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_journal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// An activity or node will be retried.
type RetryScheduledEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TargetId string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Attempt  uint32                 `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Delay before the next attempt, in milliseconds.
	DelayMs       uint64 `protobuf:"varint,3,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryScheduledEvent) Reset() {
	*x = RetryScheduledEvent{}
	mi := &file_journal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryScheduledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryScheduledEvent) ProtoMessage() {}

func (x *RetryScheduledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryScheduledEvent.ProtoReflect.Descriptor instead.
func (*RetryScheduledEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{8}
}

func (x *RetryScheduledEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *RetryScheduledEvent) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *RetryScheduledEvent) GetDelayMs() uint64 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

// The run was cancelled.
type RunCancelledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCancelledEvent) Reset() {
	*x = RunCancelledEvent{}
	mi := &file_journal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCancelledEvent) ProtoMessage() {}

func (x *RunCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCancelledEvent.ProtoReflect.Descriptor instead.
func (*RunCancelledEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{9}
}

func (x *RunCancelledEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// A single entry in the durable event journal.
type JournalEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique event id (UUIDv7 or ULID).
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Stable run id this event belongs to.
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Monotonically increasing sequence number within the run.
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// Wall-clock timestamp of recording (Unix epoch, nanoseconds).
	RecordedAtNs int64 `protobuf:"varint,4,opt,name=recorded_at_ns,json=recordedAtNs,proto3" json:"recorded_at_ns,omitempty"`
	// Exactly one event variant.
	//
	// Types that are valid to be assigned to Event:
	//
	//	*JournalEvent_RunStarted
	//	*JournalEvent_NodeEntered
	//	*JournalEvent_NodeExited
	//	*JournalEvent_ActivityRecorded
	//	*JournalEvent_HumanDecisionRequested
	//	*JournalEvent_HumanDecisionReceived
	//	*JournalEvent_RunCompleted
	//	*JournalEvent_Error
	//	*JournalEvent_RetryScheduled
	//	*JournalEvent_RunCancelled
	Event         isJournalEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalEvent) Reset() {
	*x = JournalEvent{}
	mi := &file_journal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEvent) ProtoMessage() {}

func (x *JournalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEvent.ProtoReflect.Descriptor instead.
func (*JournalEvent) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{10}
}

func (x *JournalEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *JournalEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JournalEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *JournalEvent) GetRecordedAtNs() int64 {
	if x != nil {
		return x.RecordedAtNs
	}
	return 0
}

func (x *JournalEvent) GetEvent() isJournalEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *JournalEvent) GetRunStarted() *RunStartedEvent {
	if x != nil {
		if x, ok := x.Event.(*JournalEvent_RunStarted); ok {
			return x.RunStarted
		}
	}
	return nil
}

func (x *JournalEvent) GetNodeEntered() *NodeEnteredEvent {
	if x != nil {
		if x, ok := x.Event.(*JournalEvent_NodeEntered); ok {
			return x.NodeEntered
		}
	}
	return nil
}

func (x *JournalEvent) GetNodeExited() *NodeExitedEvent {
	if x != nil {
		if x, ok := x.Event.(*JournalEvent_NodeExited); ok {
			return x.NodeExited
		}
	}
	return nil
}

func (x *JournalEvent) GetActivityRecorded() *ActivityRecordedEvent {
	if x != nil {
		if x, ok := x.Event.(*JournalEvent_ActivityRecorded); ok {
			return x.ActivityRecorded
		}
	}
	return nil
}

func (x *JournalEvent) GetHumanDecisionRequested() *HumanDecisionRequestedEvent {
	if x != nil {
		if x, ok := x.Event.(*JournalEvent_HumanDecisionRequested); ok {
			return x.HumanDecisionRequested
		}
	}
	return nil
}

func (x *JournalEvent) GetHumanDecisionReceived() *HumanDecisionReceivedEvent {
	if x != nil {
		if x, ok := x.Event.(*JournalEvent_HumanDecisionReceived); ok {
			return x.HumanDecisionReceived
		}
	}
	return nil
}

func (x *JournalEvent) GetRunCompleted() *RunCompletedEvent {
	if x != nil {
		if x, ok := x.Event.(*JournalEvent_RunCompleted); ok {
			return x.RunCompleted
		}
	}
	return nil
}

func (x *JournalEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*JournalEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *JournalEvent) GetRetryScheduled() *RetryScheduledEvent {
	if x != nil {
		if x, ok := x.Event.(*JournalEvent_RetryScheduled); ok {
			return x.RetryScheduled
		}
	}
	return nil
}

func (x *JournalEvent) GetRunCancelled() *RunCancelledEvent {
	if x != nil {
		if x, ok := x.Event.(*JournalEvent_RunCancelled); ok {
			return x.RunCancelled
		}
	}
	return nil
}

type isJournalEvent_Event interface {
	isJournalEvent_Event()
}

type JournalEvent_RunStarted struct {
	RunStarted *RunStartedEvent `protobuf:"bytes,10,opt,name=run_started,json=runStarted,proto3,oneof"`
}

type JournalEvent_NodeEntered struct {
	NodeEntered *NodeEnteredEvent `protobuf:"bytes,11,opt,name=node_entered,json=nodeEntered,proto3,oneof"`
}

type JournalEvent_NodeExited struct {
	NodeExited *NodeExitedEvent `protobuf:"bytes,12,opt,name=node_exited,json=nodeExited,proto3,oneof"`
}

type JournalEvent_ActivityRecorded struct {
	ActivityRecorded *ActivityRecordedEvent `protobuf:"bytes,13,opt,name=activity_recorded,json=activityRecorded,proto3,oneof"`
}

type JournalEvent_HumanDecisionRequested struct {
	HumanDecisionRequested *HumanDecisionRequestedEvent `protobuf:"bytes,14,opt,name=human_decision_requested,json=humanDecisionRequested,proto3,oneof"`
}

type JournalEvent_HumanDecisionReceived struct {
	HumanDecisionReceived *HumanDecisionReceivedEvent `protobuf:"bytes,15,opt,name=human_decision_received,json=humanDecisionReceived,proto3,oneof"`
}

type JournalEvent_RunCompleted struct {
	RunCompleted *RunCompletedEvent `protobuf:"bytes,16,opt,name=run_completed,json=runCompleted,proto3,oneof"`
}

type JournalEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,17,opt,name=error,proto3,oneof"`
}

type JournalEvent_RetryScheduled struct {
	RetryScheduled *RetryScheduledEvent `protobuf:"bytes,18,opt,name=retry_scheduled,json=retryScheduled,proto3,oneof"`
}

type JournalEvent_RunCancelled struct {
	RunCancelled *RunCancelledEvent `protobuf:"bytes,19,opt,name=run_cancelled,json=runCancelled,proto3,oneof"`
}

func (*JournalEvent_RunStarted) isJournalEvent_Event() {}

func (*JournalEvent_NodeEntered) isJournalEvent_Event() {}

func (*JournalEvent_NodeExited) isJournalEvent_Event() {}

func (*JournalEvent_ActivityRecorded) isJournalEvent_Event() {}

func (*JournalEvent_HumanDecisionRequested) isJournalEvent_Event() {}

func (*JournalEvent_HumanDecisionReceived) isJournalEvent_Event() {}

func (*JournalEvent_RunCompleted) isJournalEvent_Event() {}

func (*JournalEvent_Error) isJournalEvent_Event() {}

func (*JournalEvent_RetryScheduled) isJournalEvent_Event() {}

func (*JournalEvent_RunCancelled) isJournalEvent_Event() {}

var File_journal_proto protoreflect.FileDescriptor

const file_journal_proto_rawDesc = "" +
	"\n" +
	"\rjournal.proto\x12\x06ancora\"d\n" +
	"\x0fRunStartedEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"spec_bytes\x18\x02 \x01(\fR\tspecBytes\x12\x1b\n" +
	"\tspec_type\x18\x03 \x01(\tR\bspecType\"H\n" +
	"\x10NodeEnteredEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_kind\x18\x02 \x01(\tR\bnodeKind\"D\n" +
	"\x0fNodeExitedEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xbb\x01\n" +
	"\x15ActivityRecordedEvent\x12!\n" +
	"\factivity_key\x18\x01 \x01(\tR\vactivityKey\x12#\n" +
	"\ractivity_kind\x18\x02 \x01(\tR\factivityKind\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\tR\tinputJson\x12\x1f\n" +
	"\vresult_json\x18\x04 \x01(\tR\n" +
	"resultJson\x12\x1a\n" +
	"\breplayed\x18\x05 \x01(\bR\breplayed\"s\n" +
	"\x1bHumanDecisionRequestedEvent\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\x12\"\n" +
	"\rtimeout_at_ns\x18\x03 \x01(\x03R\vtimeoutAtNs\"8\n" +
	"\x1aHumanDecisionReceivedEvent\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\"4\n" +
	"\x11RunCompletedEvent\x12\x1f\n" +
	"\voutput_json\x18\x01 \x01(\tR\n" +
	"outputJson\"R\n" +
	"\n" +
	"ErrorEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"g\n" +
	"\x13RetryScheduledEvent\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\rR\aattempt\x12\x19\n" +
	"\bdelay_ms\x18\x03 \x01(\x04R\adelayMs\"+\n" +
	"\x11RunCancelledEvent\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xbd\x06\n" +
	"\fJournalEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12$\n" +
	"\x0erecorded_at_ns\x18\x04 \x01(\x03R\frecordedAtNs\x12:\n" +
	"\vrun_started\x18\n" +
	" \x01(\v2\x17.ancora.RunStartedEventH\x00R\n" +
	"runStarted\x12=\n" +
	"\fnode_entered\x18\v \x01(\v2\x18.ancora.NodeEnteredEventH\x00R\vnodeEntered\x12:\n" +
	"\vnode_exited\x18\f \x01(\v2\x17.ancora.NodeExitedEventH\x00R\n" +
	"nodeExited\x12L\n" +
	"\x11activity_recorded\x18\r \x01(\v2\x1d.ancora.ActivityRecordedEventH\x00R\x10activityRecorded\x12_\n" +
	"\x18human_decision_requested\x18\x0e \x01(\v2#.ancora.HumanDecisionRequestedEventH\x00R\x16humanDecisionRequested\x12\\\n" +
	"\x17human_decision_received\x18\x0f \x01(\v2\".ancora.HumanDecisionReceivedEventH\x00R\x15humanDecisionReceived\x12@\n" +
	"\rrun_completed\x18\x10 \x01(\v2\x19.ancora.RunCompletedEventH\x00R\frunCompleted\x12*\n" +
	"\x05error\x18\x11 \x01(\v2\x12.ancora.ErrorEventH\x00R\x05error\x12F\n" +
	"\x0fretry_scheduled\x18\x12 \x01(\v2\x1b.ancora.RetryScheduledEventH\x00R\x0eretryScheduled\x12@\n" +
	"\rrun_cancelled\x18\x13 \x01(\v2\x19.ancora.RunCancelledEventH\x00R\frunCancelledB\a\n" +
	"\x05eventBG\n" +
	"\n" +
	"dev.ancoraB\tJournalPbZ.github.com/YASSERRMD/Ancora/bindings/go/ancorab\x06proto3"

var (
	file_journal_proto_rawDescOnce sync.Once
	file_journal_proto_rawDescData []byte
)

func file_journal_proto_rawDescGZIP() []byte {
	file_journal_proto_rawDescOnce.Do(func() {
		file_journal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_journal_proto_rawDesc), len(file_journal_proto_rawDesc)))
	})
	return file_journal_proto_rawDescData
}

var file_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_journal_proto_goTypes = []any{
	(*RunStartedEvent)(nil),             // 0: ancora.RunStartedEvent
	(*NodeEnteredEvent)(nil),            // 1: ancora.NodeEnteredEvent
	(*NodeExitedEvent)(nil),             // 2: ancora.NodeExitedEvent
	(*ActivityRecordedEvent)(nil),       // 3: ancora.ActivityRecordedEvent
	(*HumanDecisionRequestedEvent)(nil), // 4: ancora.HumanDecisionRequestedEvent
	(*HumanDecisionReceivedEvent)(nil),  // 5: ancora.HumanDecisionReceivedEvent
	(*RunCompletedEvent)(nil),           // 6: ancora.RunCompletedEvent
	(*ErrorEvent)(nil),                  // 7: ancora.ErrorEvent
	(*RetryScheduledEvent)(nil),         // 8: ancora.RetryScheduledEvent
	(*RunCancelledEvent)(nil),           // 9: ancora.RunCancelledEvent
	(*JournalEvent)(nil),                // 10: ancora.JournalEvent
}
var file_journal_proto_depIdxs = []int32{
	0,  // 0: ancora.JournalEvent.run_started:type_name -> ancora.RunStartedEvent
	1,  // 1: ancora.JournalEvent.node_entered:type_name -> ancora.NodeEnteredEvent
	2,  // 2: ancora.JournalEvent.node_exited:type_name -> ancora.NodeExitedEvent
	3,  // 3: ancora.JournalEvent.activity_recorded:type_name -> ancora.ActivityRecordedEvent
	4,  // 4: ancora.JournalEvent.human_decision_requested:type_name -> ancora.HumanDecisionRequestedEvent
	5,  // 5: ancora.JournalEvent.human_decision_received:type_name -> ancora.HumanDecisionReceivedEvent
	6,  // 6: ancora.JournalEvent.run_completed:type_name -> ancora.RunCompletedEvent
	7,  // 7: ancora.JournalEvent.error:type_name -> ancora.ErrorEvent
	8,  // 8: ancora.JournalEvent.retry_scheduled:type_name -> ancora.RetryScheduledEvent
	9,  // 9: ancora.JournalEvent.run_cancelled:type_name -> ancora.RunCancelledEvent
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_journal_proto_init() }
func file_journal_proto_init() {
	if File_journal_proto != nil {
		return
	}
	file_journal_proto_msgTypes[10].OneofWrappers = []any{
		(*JournalEvent_RunStarted)(nil),
		(*JournalEvent_NodeEntered)(nil),
		(*JournalEvent_NodeExited)(nil),
		(*JournalEvent_ActivityRecorded)(nil),
		(*JournalEvent_HumanDecisionRequested)(nil),
		(*JournalEvent_HumanDecisionReceived)(nil),
		(*JournalEvent_RunCompleted)(nil),
		(*JournalEvent_Error)(nil),
		(*JournalEvent_RetryScheduled)(nil),
		(*JournalEvent_RunCancelled)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_journal_proto_rawDesc), len(file_journal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_journal_proto_goTypes,
		DependencyIndexes: file_journal_proto_depIdxs,
		MessageInfos:      file_journal_proto_msgTypes,
	}.Build()
	File_journal_proto = out.File
	file_journal_proto_goTypes = nil
	file_journal_proto_depIdxs = nil
}
