// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: messages.proto

package ancora

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_SYSTEM      Role = 1
	Role_ROLE_USER        Role = 2
	Role_ROLE_ASSISTANT   Role = 3
	Role_ROLE_TOOL        Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_SYSTEM",
		2: "ROLE_USER",
		3: "ROLE_ASSISTANT",
		4: "ROLE_TOOL",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_SYSTEM":      1,
		"ROLE_USER":        2,
		"ROLE_ASSISTANT":   3,
		"ROLE_TOOL":        4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

// Plain UTF-8 text.
type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// A request from the model to invoke a tool.
type ToolCallContent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName   string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// JSON-encoded arguments.
	ArgumentsJson string `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallContent) Reset() {
	*x = ToolCallContent{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallContent) ProtoMessage() {}

func (x *ToolCallContent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallContent.ProtoReflect.Descriptor instead.
func (*ToolCallContent) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCallContent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCallContent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallContent) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

// The result of a tool invocation, returned to the model.
type ToolResultContent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	// JSON-encoded result value.
	ResultJson string `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// Set to true when the tool returned an error.
	IsError       bool `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultContent) Reset() {
	*x = ToolResultContent{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultContent) ProtoMessage() {}

func (x *ToolResultContent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultContent.ProtoReflect.Descriptor instead.
func (*ToolResultContent) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ToolResultContent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResultContent) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolResultContent) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

// A still image, either inline or by reference.
type ImageContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*ImageContent_InlineBase64
	//	*ImageContent_Url
	Source        isImageContent_Source `protobuf_oneof:"source"`
	MediaType     string                `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContent) Reset() {
	*x = ImageContent{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContent) ProtoMessage() {}

func (x *ImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContent.ProtoReflect.Descriptor instead.
func (*ImageContent) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ImageContent) GetSource() isImageContent_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ImageContent) GetInlineBase64() string {
	if x != nil {
		if x, ok := x.Source.(*ImageContent_InlineBase64); ok {
			return x.InlineBase64
		}
	}
	return ""
}

func (x *ImageContent) GetUrl() string {
	if x != nil {
		if x, ok := x.Source.(*ImageContent_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *ImageContent) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type isImageContent_Source interface {
	isImageContent_Source()
}

type ImageContent_InlineBase64 struct {
	// Base-64 encoded bytes with MIME type prefix, e.g. "image/png;base64,..."
	InlineBase64 string `protobuf:"bytes,1,opt,name=inline_base64,json=inlineBase64,proto3,oneof"`
}

type ImageContent_Url struct {
	// A URL pointing to a publicly accessible image.
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*ImageContent_InlineBase64) isImageContent_Source() {}

func (*ImageContent_Url) isImageContent_Source() {}

// An audio clip, either inline or by reference.
type AudioContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*AudioContent_InlineBase64
	//	*AudioContent_Url
	Source        isAudioContent_Source `protobuf_oneof:"source"`
	MediaType     string                `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioContent) Reset() {
	*x = AudioContent{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioContent) ProtoMessage() {}

func (x *AudioContent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioContent.ProtoReflect.Descriptor instead.
func (*AudioContent) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *AudioContent) GetSource() isAudioContent_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *AudioContent) GetInlineBase64() string {
	if x != nil {
		if x, ok := x.Source.(*AudioContent_InlineBase64); ok {
			return x.InlineBase64
		}
	}
	return ""
}

func (x *AudioContent) GetUrl() string {
	if x != nil {
		if x, ok := x.Source.(*AudioContent_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *AudioContent) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type isAudioContent_Source interface {
	isAudioContent_Source()
}

type AudioContent_InlineBase64 struct {
	InlineBase64 string `protobuf:"bytes,1,opt,name=inline_base64,json=inlineBase64,proto3,oneof"`
}

type AudioContent_Url struct {
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*AudioContent_InlineBase64) isAudioContent_Source() {}

func (*AudioContent_Url) isAudioContent_Source() {}

// A document (PDF, plain text file, etc.).
type DocumentContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*DocumentContent_InlineBase64
	//	*DocumentContent_Url
	Source        isDocumentContent_Source `protobuf_oneof:"source"`
	MediaType     string                   `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Filename      string                   `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentContent) Reset() {
	*x = DocumentContent{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentContent) ProtoMessage() {}

func (x *DocumentContent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentContent.ProtoReflect.Descriptor instead.
func (*DocumentContent) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentContent) GetSource() isDocumentContent_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DocumentContent) GetInlineBase64() string {
	if x != nil {
		if x, ok := x.Source.(*DocumentContent_InlineBase64); ok {
			return x.InlineBase64
		}
	}
	return ""
}

func (x *DocumentContent) GetUrl() string {
	if x != nil {
		if x, ok := x.Source.(*DocumentContent_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *DocumentContent) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *DocumentContent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type isDocumentContent_Source interface {
	isDocumentContent_Source()
}

type DocumentContent_InlineBase64 struct {
	InlineBase64 string `protobuf:"bytes,1,opt,name=inline_base64,json=inlineBase64,proto3,oneof"`
}

type DocumentContent_Url struct {
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*DocumentContent_InlineBase64) isDocumentContent_Source() {}

func (*DocumentContent_Url) isDocumentContent_Source() {}

// One content block within a message.
type ContentBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Block:
	//
	//	*ContentBlock_Text
	//	*ContentBlock_ToolCall
	//	*ContentBlock_ToolResult
	//	*ContentBlock_Image
	//	*ContentBlock_Audio
	//	*ContentBlock_Document
	Block         isContentBlock_Block `protobuf_oneof:"block"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlock) Reset() {
	*x = ContentBlock{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlock) ProtoMessage() {}

func (x *ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlock.ProtoReflect.Descriptor instead.
func (*ContentBlock) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ContentBlock) GetBlock() isContentBlock_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ContentBlock) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ContentBlock) GetToolCall() *ToolCallContent {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *ContentBlock) GetToolResult() *ToolResultContent {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *ContentBlock) GetImage() *ImageContent {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ContentBlock) GetAudio() *AudioContent {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *ContentBlock) GetDocument() *DocumentContent {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Document); ok {
			return x.Document
		}
	}
	return nil
}

type isContentBlock_Block interface {
	isContentBlock_Block()
}

type ContentBlock_Text struct {
	Text *TextContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentBlock_ToolCall struct {
	ToolCall *ToolCallContent `protobuf:"bytes,2,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type ContentBlock_ToolResult struct {
	ToolResult *ToolResultContent `protobuf:"bytes,3,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type ContentBlock_Image struct {
	Image *ImageContent `protobuf:"bytes,4,opt,name=image,proto3,oneof"`
}

type ContentBlock_Audio struct {
	Audio *AudioContent `protobuf:"bytes,5,opt,name=audio,proto3,oneof"`
}

type ContentBlock_Document struct {
	Document *DocumentContent `protobuf:"bytes,6,opt,name=document,proto3,oneof"`
}

func (*ContentBlock_Text) isContentBlock_Block() {}

func (*ContentBlock_ToolCall) isContentBlock_Block() {}

func (*ContentBlock_ToolResult) isContentBlock_Block() {}

func (*ContentBlock_Image) isContentBlock_Block() {}

func (*ContentBlock_Audio) isContentBlock_Block() {}

func (*ContentBlock_Document) isContentBlock_Block() {}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputTokens      uint64                 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens     uint64                 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheReadTokens  uint64                 `protobuf:"varint,3,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	CacheWriteTokens uint64                 `protobuf:"varint,4,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *TokenUsage) GetInputTokens() uint64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsage) GetOutputTokens() uint64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *TokenUsage) GetCacheReadTokens() uint64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *TokenUsage) GetCacheWriteTokens() uint64 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

// Cost amounts are in millionths of a US cent (micro-cents) to avoid
// floating-point in the wire format.
type Cost struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InputMicroCents      uint64                 `protobuf:"varint,1,opt,name=input_micro_cents,json=inputMicroCents,proto3" json:"input_micro_cents,omitempty"`
	OutputMicroCents     uint64                 `protobuf:"varint,2,opt,name=output_micro_cents,json=outputMicroCents,proto3" json:"output_micro_cents,omitempty"`
	CacheReadMicroCents  uint64                 `protobuf:"varint,3,opt,name=cache_read_micro_cents,json=cacheReadMicroCents,proto3" json:"cache_read_micro_cents,omitempty"`
	CacheWriteMicroCents uint64                 `protobuf:"varint,4,opt,name=cache_write_micro_cents,json=cacheWriteMicroCents,proto3" json:"cache_write_micro_cents,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Cost) Reset() {
	*x = Cost{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cost) ProtoMessage() {}

func (x *Cost) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cost.ProtoReflect.Descriptor instead.
func (*Cost) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Cost) GetInputMicroCents() uint64 {
	if x != nil {
		return x.InputMicroCents
	}
	return 0
}

func (x *Cost) GetOutputMicroCents() uint64 {
	if x != nil {
		return x.OutputMicroCents
	}
	return 0
}

func (x *Cost) GetCacheReadMicroCents() uint64 {
	if x != nil {
		return x.CacheReadMicroCents
	}
	return 0
}

func (x *Cost) GetCacheWriteMicroCents() uint64 {
	if x != nil {
		return x.CacheWriteMicroCents
	}
	return 0
}

// A single turn in a conversation.
type Message struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role    Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=ancora.Role" json:"role,omitempty"`
	Content []*ContentBlock        `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	// Wall-clock timestamp of creation (Unix epoch, nanoseconds).
	CreatedAtNs int64       `protobuf:"varint,4,opt,name=created_at_ns,json=createdAtNs,proto3" json:"created_at_ns,omitempty"`
	Usage       *TokenUsage `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	Cost        *Cost       `protobuf:"bytes,6,opt,name=cost,proto3" json:"cost,omitempty"`
	// Opaque model identifier that produced this message.
	ModelId       string `protobuf:"bytes,7,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetCreatedAtNs() int64 {
	if x != nil {
		return x.CreatedAtNs
	}
	return 0
}

func (x *Message) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Message) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Message) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x06ancora\"!\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"w\n" +
	"\x0fToolCallContent\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"q\n" +
	"\x11ToolResultContent\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\"r\n" +
	"\fImageContent\x12%\n" +
	"\rinline_base64\x18\x01 \x01(\tH\x00R\finlineBase64\x12\x12\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03url\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaTypeB\b\n" +
	"\x06source\"r\n" +
	"\fAudioContent\x12%\n" +
	"\rinline_base64\x18\x01 \x01(\tH\x00R\finlineBase64\x12\x12\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03url\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaTypeB\b\n" +
	"\x06source\"\x91\x01\n" +
	"\x0fDocumentContent\x12%\n" +
	"\rinline_base64\x18\x01 \x01(\tH\x00R\finlineBase64\x12\x12\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03url\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilenameB\b\n" +
	"\x06source\"\xcb\x02\n" +
	"\fContentBlock\x12)\n" +
	"\x04text\x18\x01 \x01(\v2\x13.ancora.TextContentH\x00R\x04text\x126\n" +
	"\ttool_call\x18\x02 \x01(\v2\x17.ancora.ToolCallContentH\x00R\btoolCall\x12<\n" +
	"\vtool_result\x18\x03 \x01(\v2\x19.ancora.ToolResultContentH\x00R\n" +
	"toolResult\x12,\n" +
	"\x05image\x18\x04 \x01(\v2\x14.ancora.ImageContentH\x00R\x05image\x12,\n" +
	"\x05audio\x18\x05 \x01(\v2\x14.ancora.AudioContentH\x00R\x05audio\x125\n" +
	"\bdocument\x18\x06 \x01(\v2\x17.ancora.DocumentContentH\x00R\bdocumentB\a\n" +
	"\x05block\"\xae\x01\n" +
	"\n" +
	"TokenUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x04R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x04R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x03 \x01(\x04R\x0fcacheReadTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x04 \x01(\x04R\x10cacheWriteTokens\"\xcc\x01\n" +
	"\x04Cost\x12*\n" +
	"\x11input_micro_cents\x18\x01 \x01(\x04R\x0finputMicroCents\x12,\n" +
	"\x12output_micro_cents\x18\x02 \x01(\x04R\x10outputMicroCents\x123\n" +
	"\x16cache_read_micro_cents\x18\x03 \x01(\x04R\x13cacheReadMicroCents\x125\n" +
	"\x17cache_write_micro_cents\x18\x04 \x01(\x04R\x14cacheWriteMicroCents\"\xf6\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\x04role\x18\x02 \x01(\x0e2\f.ancora.RoleR\x04role\x12.\n" +
	"\acontent\x18\x03 \x03(\v2\x14.ancora.ContentBlockR\acontent\x12\"\n" +
	"\rcreated_at_ns\x18\x04 \x01(\x03R\vcreatedAtNs\x12(\n" +
	"\x05usage\x18\x05 \x01(\v2\x12.ancora.TokenUsageR\x05usage\x12 \n" +
	"\x04cost\x18\x06 \x01(\v2\f.ancora.CostR\x04cost\x12\x19\n" +
	"\bmodel_id\x18\a \x01(\tR\amodelId*_\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_SYSTEM\x10\x01\x12\r\n" +
	"\tROLE_USER\x10\x02\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x03\x12\r\n" +
	"\tROLE_TOOL\x10\x04BH\n" +
	"\n" +
	"dev.ancoraB\n" +
	"MessagesPbZ.github.com/YASSERRMD/Ancora/bindings/go/ancorab\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_messages_proto_goTypes = []any{
	(Role)(0),                 // 0: ancora.Role
	(*TextContent)(nil),       // 1: ancora.TextContent
	(*ToolCallContent)(nil),   // 2: ancora.ToolCallContent
	(*ToolResultContent)(nil), // 3: ancora.ToolResultContent
	(*ImageContent)(nil),      // 4: ancora.ImageContent
	(*AudioContent)(nil),      // 5: ancora.AudioContent
	(*DocumentContent)(nil),   // 6: ancora.DocumentContent
	(*ContentBlock)(nil),      // 7: ancora.ContentBlock
	(*TokenUsage)(nil),        // 8: ancora.TokenUsage
	(*Cost)(nil),              // 9: ancora.Cost
	(*Message)(nil),           // 10: ancora.Message
}
var file_messages_proto_depIdxs = []int32{
	1,  // 0: ancora.ContentBlock.text:type_name -> ancora.TextContent
	2,  // 1: ancora.ContentBlock.tool_call:type_name -> ancora.ToolCallContent
	3,  // 2: ancora.ContentBlock.tool_result:type_name -> ancora.ToolResultContent
	4,  // 3: ancora.ContentBlock.image:type_name -> ancora.ImageContent
	5,  // 4: ancora.ContentBlock.audio:type_name -> ancora.AudioContent
	6,  // 5: ancora.ContentBlock.document:type_name -> ancora.DocumentContent
	0,  // 6: ancora.Message.role:type_name -> ancora.Role
	7,  // 7: ancora.Message.content:type_name -> ancora.ContentBlock
	8,  // 8: ancora.Message.usage:type_name -> ancora.TokenUsage
	9,  // 9: ancora.Message.cost:type_name -> ancora.Cost
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*ImageContent_InlineBase64)(nil),
		(*ImageContent_Url)(nil),
	}
	file_messages_proto_msgTypes[4].OneofWrappers = []any{
		(*AudioContent_InlineBase64)(nil),
		(*AudioContent_Url)(nil),
	}
	file_messages_proto_msgTypes[5].OneofWrappers = []any{
		(*DocumentContent_InlineBase64)(nil),
		(*DocumentContent_Url)(nil),
	}
	file_messages_proto_msgTypes[6].OneofWrappers = []any{
		(*ContentBlock_Text)(nil),
		(*ContentBlock_ToolCall)(nil),
		(*ContentBlock_ToolResult)(nil),
		(*ContentBlock_Image)(nil),
		(*ContentBlock_Audio)(nil),
		(*ContentBlock_Document)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
