"""Type stubs for the ancora package."""

from enum import IntEnum
from typing import Any, AsyncGenerator, AsyncIterator, Iterator, List, Optional, Type

class AncorError(Exception):
    def __init__(self, message: str) -> None: ...

class Runtime:
    def __init__(self) -> None: ...
    def free(self) -> None: ...
    @property
    def is_freed(self) -> bool: ...
    def start_run(self, spec_bytes: bytes) -> str: ...
    def poll_run(self, run_id: str) -> Optional[bytes]: ...
    def resume_run(self, run_id: str, decision: bytes) -> None: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> "Runtime": ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[object],
    ) -> bool: ...

class EffectClass(IntEnum):
    UNSPECIFIED: int
    PURE: int
    READ: int
    WRITE: int

class ToolSpec:
    name: str
    description: str
    input_schema_json: str
    output_schema_json: str
    effect_class: EffectClass
    idempotency_key_template: str
    def __init__(self, *, name: str = ..., description: str = ..., **kwargs: object) -> None: ...

class RetryPolicy:
    max_attempts: int
    initial_backoff_ms: int
    max_backoff_ms: int
    jitter: float
    def __init__(self, *, max_attempts: int = ..., **kwargs: object) -> None: ...

class AgentSpec:
    name: str
    model_id: str
    instructions: str
    output_schema_json: str
    tools: List[ToolSpec]
    max_steps: int
    model_retry: Optional[RetryPolicy]
    model_params_json: str
    def __init__(self, *, name: str = ..., model_id: str = ..., **kwargs: object) -> None: ...
    def wire_bytes(self) -> bytes: ...

class ToolSpecBuilder:
    def with_name(self, name: str) -> "ToolSpecBuilder": ...
    def with_description(self, description: str) -> "ToolSpecBuilder": ...
    def with_effect_class(self, effect_class: EffectClass) -> "ToolSpecBuilder": ...
    def build(self) -> ToolSpec: ...

class AgentSpecBuilder:
    def with_name(self, name: str) -> "AgentSpecBuilder": ...
    def with_model_id(self, model_id: str) -> "AgentSpecBuilder": ...
    def with_instructions(self, instructions: str) -> "AgentSpecBuilder": ...
    def with_tool(self, tool: ToolSpec) -> "AgentSpecBuilder": ...
    def with_max_steps(self, max_steps: int) -> "AgentSpecBuilder": ...
    def with_model_retry(self, retry: RetryPolicy) -> "AgentSpecBuilder": ...
    def build(self) -> AgentSpec: ...

class StreamEvent:
    kind: str
    run_id: str
    text: Optional[str]
    spec: Optional[str]
    decision: Optional[str]
    def __init__(self, *, kind: str = ..., run_id: str = ..., **kwargs: Any) -> None: ...
    @classmethod
    def from_bytes(cls, data: bytes) -> "StreamEvent": ...
    @property
    def is_token(self) -> bool: ...
    @property
    def is_started(self) -> bool: ...
    @property
    def is_completed(self) -> bool: ...

class MemoryStore:
    def read(self, key: str, default: Any = ...) -> Any: ...
    def write(self, key: str, value: Any) -> None: ...
    def delete(self, key: str) -> None: ...
    def clear(self) -> None: ...
    def update(self, mapping: dict) -> None: ...
    def pop(self, key: str, default: Any = ...) -> Any: ...
    @property
    def keys(self) -> list[str]: ...
    @property
    def values(self) -> list[Any]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __repr__(self) -> str: ...

class Run:
    def __init__(self, rt: "Runtime", run_id: str) -> None: ...
    @property
    def run_id(self) -> str: ...
    def __repr__(self) -> str: ...
    def __aiter__(self) -> "Run": ...
    async def __anext__(self) -> bytes: ...
    async def resume(self, decision: bytes = ...) -> None: ...
    async def drain_events(self) -> list[bytes]: ...
    def stream_events(self) -> AsyncGenerator[bytes, None]: ...
    def stream_tokens(self) -> AsyncGenerator[str, None]: ...

class Agent:
    def __init__(
        self,
        rt: "Runtime",
        spec: AgentSpec,
        registry: Optional["ToolRegistry"] = ...,
        memory: Optional["MemoryStore"] = ...,
    ) -> None: ...
    @property
    def spec(self) -> AgentSpec: ...
    @property
    def registry(self) -> Optional["ToolRegistry"]: ...
    @property
    def memory(self) -> "MemoryStore": ...
    def register_tool(self, t: "Tool") -> None: ...
    async def run(self) -> Run: ...

class Tool:
    def __init__(self, fn: Any, spec: ToolSpec) -> None: ...
    @property
    def spec(self) -> ToolSpec: ...
    @property
    def name(self) -> str: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def call_with_json(self, args_json: str) -> Any: ...
    def __repr__(self) -> str: ...

class ToolRegistry:
    def register(self, tool: "Tool") -> None: ...
    def get(self, name: str) -> Optional["Tool"]: ...
    def dispatch(self, name: str, args_json: str = ...) -> Any: ...
    async def adispatch(self, name: str, args_json: str = ...) -> Any: ...
    def all_specs(self) -> list[ToolSpec]: ...
    @property
    def names(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...

def tool(
    fn: Optional[Any] = ...,
    *,
    name: Optional[str] = ...,
    description: Optional[str] = ...,
    effect_class: EffectClass = ...,
) -> Any: ...

def to_wire_bytes(spec: AgentSpec) -> bytes: ...
def from_wire_bytes(data: bytes) -> AgentSpec: ...
def version() -> str: ...
