//! Core model types for small-language-model orchestration.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Capability tier of a language model.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum ModelTier {
    /// Small / local model (e.g., Phi-3 mini, Gemma 2B).
    Small,
    /// Medium model (e.g., Mistral 7B, Llama 8B).
    Medium,
    /// Large model (e.g., 70B+ parameter models).
    Large,
}

/// A language-model descriptor used by the orchestrator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelSpec {
    /// Unique identifier for the model.
    pub id: String,
    /// Human-readable display name.
    pub display_name: String,
    /// Capability tier.
    pub tier: ModelTier,
    /// Maximum context window in tokens.
    pub context_window: usize,
    /// Whether the model supports native JSON mode / constrained decoding.
    pub supports_json_mode: bool,
    /// Whether the model supports native tool-call syntax.
    pub supports_tool_calls: bool,
    /// Arbitrary key-value metadata (e.g., quantization level, provider name).
    pub metadata: HashMap<String, String>,
}

impl ModelSpec {
    /// Create a minimal SLM spec for testing/defaults.
    pub fn small(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            display_name: String::from("Small Model"),
            tier: ModelTier::Small,
            context_window: 4096,
            supports_json_mode: false,
            supports_tool_calls: false,
            metadata: HashMap::new(),
        }
    }

    /// Create a minimal large-model spec for escalation.
    pub fn large(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            display_name: String::from("Large Model"),
            tier: ModelTier::Large,
            context_window: 128_000,
            supports_json_mode: true,
            supports_tool_calls: true,
            metadata: HashMap::new(),
        }
    }

    /// Returns `true` if this model is in the small tier.
    pub fn is_slm(&self) -> bool {
        self.tier == ModelTier::Small
    }
}

/// A single turn in a conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Role of the speaker.
    pub role: Role,
    /// Text content of the message.
    pub content: String,
}

impl Message {
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: Role::System,
            content: content.into(),
        }
    }
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: content.into(),
        }
    }
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: Role::Assistant,
            content: content.into(),
        }
    }
}

/// Speaker role in a conversation turn.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    User,
    Assistant,
}

/// A completion request directed at a specific model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionRequest {
    /// Target model.
    pub model: ModelSpec,
    /// Message history including the new user turn.
    pub messages: Vec<Message>,
    /// Optional temperature override (0.0 – 1.0).
    pub temperature: Option<f32>,
    /// Maximum tokens to generate.
    pub max_tokens: Option<usize>,
}

/// A raw completion response from a model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionResponse {
    /// Raw text generated by the model.
    pub text: String,
    /// Model that produced this response.
    pub model_id: String,
    /// Whether generation was stopped due to token limit.
    pub truncated: bool,
}

impl CompletionResponse {
    pub fn new(text: impl Into<String>, model_id: impl Into<String>) -> Self {
        Self {
            text: text.into(),
            model_id: model_id.into(),
            truncated: false,
        }
    }
}
