/// Conformance suite wiring for the pgvector SQL generation layer.
///
/// These tests verify that every SQL template generated by this module is
/// structurally correct: it contains the right keywords, placeholders, and
/// table references. They run offline without a live Postgres server.
///
/// Integration tests that need an actual pgvector server are collected in
/// `pgvector_integration.rs` and are all `#[ignore]` unless
/// `TEST_DATABASE_URL` is set in the environment.

#[cfg(test)]
mod conformance {
    use crate::backends::pgvector::*;
    use crate::vector_store::{Filter, PayloadValue};

    // -- DDL surface ---------------------------------------------------------

    #[test]
    fn conformance_create_table_has_all_columns() {
        let sql = create_table_sql("conformance_test", 768);
        assert!(sql.contains("id BIGINT PRIMARY KEY"), "SQL: {sql}");
        assert!(sql.contains("vector(768)"), "SQL: {sql}");
        assert!(sql.contains("payload JSONB"), "SQL: {sql}");
    }

    #[test]
    fn conformance_drop_table_references_table_name() {
        let sql = drop_table_sql("conformance_test");
        assert!(sql.contains("conformance_test"), "SQL: {sql}");
    }

    #[test]
    fn conformance_count_sql_references_table_name() {
        let sql = count_sql("conformance_test");
        assert!(sql.contains("conformance_test"), "SQL: {sql}");
        assert!(sql.contains("COUNT(*)"), "SQL: {sql}");
    }

    // -- Index surface -------------------------------------------------------

    #[test]
    fn conformance_hnsw_defaults_within_valid_range() {
        let params = HnswParams::default();
        assert!(HnswParams::new(params.m, params.ef_construct).is_ok());
    }

    #[test]
    fn conformance_ivfflat_defaults_within_valid_range() {
        let params = IvfFlatParams::default();
        assert!(params.probes <= params.lists);
    }

    // -- Upsert surface ------------------------------------------------------

    #[test]
    fn conformance_upsert_sql_contains_all_columns() {
        let sql = upsert_sql("conformance_test");
        assert!(sql.contains("id"), "SQL: {sql}");
        assert!(sql.contains("embedding"), "SQL: {sql}");
        assert!(sql.contains("payload"), "SQL: {sql}");
    }

    // -- Query surface -------------------------------------------------------

    #[test]
    fn conformance_cosine_query_is_ordered_by_distance() {
        let sql = cosine_query_sql("conformance_test", 10, 0);
        assert!(sql.contains("ORDER BY embedding <=>"), "SQL: {sql}");
    }

    #[test]
    fn conformance_dot_query_orders_by_inner_product() {
        let sql = dot_query_sql("conformance_test", 10);
        assert!(sql.contains("ORDER BY embedding <#>"), "SQL: {sql}");
    }

    #[test]
    fn conformance_l2_query_orders_by_euclidean() {
        let sql = l2_query_sql("conformance_test", 10);
        assert!(sql.contains("ORDER BY embedding <->"), "SQL: {sql}");
    }

    // -- Filter surface ------------------------------------------------------

    #[test]
    fn conformance_filter_eq_produces_param() {
        let f = Filter::Eq("source".to_owned(), PayloadValue::String("test".to_owned()));
        let (_, params) = filter_to_sql(&f, 0);
        assert!(!params.is_empty());
    }

    #[test]
    fn conformance_filter_null_produces_no_param() {
        let f = Filter::Eq("field".to_owned(), PayloadValue::Null);
        let (sql, params) = filter_to_sql(&f, 0);
        assert!(sql.contains("IS NULL"), "SQL: {sql}");
        assert!(params.is_empty());
    }

    // -- Hybrid surface ------------------------------------------------------

    #[test]
    fn conformance_hybrid_query_has_both_signals() {
        let sql = hybrid_query_sql("conformance_test", 10, 0.5);
        assert!(sql.contains("<=>"), "SQL: {sql}");
        assert!(sql.contains("ts_rank"), "SQL: {sql}");
    }

    // -- Batch surface -------------------------------------------------------

    #[test]
    fn conformance_split_into_batches_preserves_all_items() {
        let items: Vec<i32> = (0..100).collect();
        let batches = split_into_batches(items.clone(), 10);
        let recovered: Vec<i32> = batches.into_iter().flatten().collect();
        assert_eq!(recovered, items);
    }

    // -- Journal surface -----------------------------------------------------

    #[test]
    fn conformance_journal_table_has_unique_key() {
        let sql = create_journal_table_sql("journal_test");
        assert!(sql.contains("PRIMARY KEY"), "SQL: {sql}");
    }
}
