//! Conformance surface tests for the Weaviate REST/GraphQL layer.
//!
//! Verifies structural correctness of every request shape generated by the
//! weaviate module. No live Weaviate server needed.

#![cfg(test)]

use crate::backends::weaviate::*;

// -- URL surface ---------------------------------------------------------

#[test]
fn conformance_all_urls_include_v1_prefix() {
    let base = "http://localhost:8080";
    for url in [
        schema_url(base),
        objects_url(base),
        graphql_url(base),
        batch_objects_url(base),
        readiness_url(base),
        meta_url(base),
    ] {
        assert!(url.contains("/v1/"), "url missing /v1/: {url}");
    }
}

// -- Schema surface ------------------------------------------------------

#[test]
fn conformance_class_name_appears_in_body() {
    let body = create_class_body("MyClass", "desc", "none");
    assert_eq!(body["class"], "MyClass");
}

#[test]
fn conformance_properties_array_is_empty_by_default() {
    let body = create_class_body("MyClass", "desc", "none");
    assert!(body["properties"].as_array().unwrap().is_empty());
}

// -- Object CRUD surface -------------------------------------------------

#[test]
fn conformance_create_object_has_class_and_properties() {
    let props = serde_json::json!({"title": "test"});
    let body = create_object_body("Document", &props, None);
    assert_eq!(body["class"], "Document");
    assert!(body["properties"].is_object());
}

// -- Batch surface -------------------------------------------------------

#[test]
fn conformance_batch_objects_body_wraps_in_objects_key() {
    let objs = vec![("Document".to_owned(), serde_json::json!({}), None)];
    let body = batch_objects_body(&objs);
    assert!(body["objects"].is_array());
}

// -- GraphQL surface -----------------------------------------------------

#[test]
fn conformance_graphql_near_vector_has_get() {
    let body = graphql_near_vector_query("Document", &[0.1f32], 5, &["title"]);
    let q = body["query"].as_str().unwrap();
    assert!(q.contains("Get"), "query: {q}");
}

#[test]
fn conformance_graphql_hybrid_has_hybrid_keyword() {
    let body = graphql_hybrid_query("Document", "search", None, 0.5, 5, &["title"]);
    let q = body["query"].as_str().unwrap();
    assert!(q.contains("hybrid"), "query: {q}");
}

// -- Filter surface ------------------------------------------------------

#[test]
fn conformance_where_filter_has_path_and_operator() {
    let f = where_filter_text("source", "Equal", "wiki");
    assert!(f["path"].is_array());
    assert!(f["operator"].is_string());
}

#[test]
fn conformance_where_and_has_operands_array() {
    let f1 = where_filter_text("a", "Equal", "x");
    let f2 = where_filter_int("b", "GreaterThan", 10);
    let compound = where_filter_and(&[f1, f2]);
    assert_eq!(compound["operator"], "And");
    assert!(compound["operands"].is_array());
}

// -- Error surface -------------------------------------------------------

#[test]
fn conformance_404_error_is_not_found() {
    let err = WeaviateError::from_response(404, "{}");
    assert!(matches!(err, WeaviateError::NotFound(_)));
}

#[test]
fn conformance_transient_500() {
    let err = WeaviateError::from_response(500, "error");
    assert!(err.is_transient());
}

// -- Retry surface -------------------------------------------------------

#[test]
fn conformance_retry_delay_is_increasing() {
    let d0 = weaviate_retry_delay_ms(0);
    let d1 = weaviate_retry_delay_ms(1);
    let d2 = weaviate_retry_delay_ms(2);
    assert!(d1 > d0 && d2 > d1);
}
