// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: ancora.proto

package runservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentSpec     []byte                 `protobuf:"bytes,1,opt,name=agent_spec,json=agentSpec,proto3" json:"agent_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunRequest) Reset() {
	*x = StartRunRequest{}
	mi := &file_ancora_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunRequest) ProtoMessage() {}

func (x *StartRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ancora_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunRequest.ProtoReflect.Descriptor instead.
func (*StartRunRequest) Descriptor() ([]byte, []int) {
	return file_ancora_proto_rawDescGZIP(), []int{0}
}

func (x *StartRunRequest) GetAgentSpec() []byte {
	if x != nil {
		return x.AgentSpec
	}
	return nil
}

type StartRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunResponse) Reset() {
	*x = StartRunResponse{}
	mi := &file_ancora_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunResponse) ProtoMessage() {}

func (x *StartRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ancora_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunResponse.ProtoReflect.Descriptor instead.
func (*StartRunResponse) Descriptor() ([]byte, []int) {
	return file_ancora_proto_rawDescGZIP(), []int{1}
}

func (x *StartRunResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type PollRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRunRequest) Reset() {
	*x = PollRunRequest{}
	mi := &file_ancora_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRunRequest) ProtoMessage() {}

func (x *PollRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ancora_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRunRequest.ProtoReflect.Descriptor instead.
func (*PollRunRequest) Descriptor() ([]byte, []int) {
	return file_ancora_proto_rawDescGZIP(), []int{2}
}

func (x *PollRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type PollRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRunResponse) Reset() {
	*x = PollRunResponse{}
	mi := &file_ancora_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRunResponse) ProtoMessage() {}

func (x *PollRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ancora_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRunResponse.ProtoReflect.Descriptor instead.
func (*PollRunResponse) Descriptor() ([]byte, []int) {
	return file_ancora_proto_rawDescGZIP(), []int{3}
}

func (x *PollRunResponse) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type ResumeRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Decision      []byte                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRunRequest) Reset() {
	*x = ResumeRunRequest{}
	mi := &file_ancora_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRunRequest) ProtoMessage() {}

func (x *ResumeRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ancora_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRunRequest.ProtoReflect.Descriptor instead.
func (*ResumeRunRequest) Descriptor() ([]byte, []int) {
	return file_ancora_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ResumeRunRequest) GetDecision() []byte {
	if x != nil {
		return x.Decision
	}
	return nil
}

type ResumeRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRunResponse) Reset() {
	*x = ResumeRunResponse{}
	mi := &file_ancora_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRunResponse) ProtoMessage() {}

func (x *ResumeRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ancora_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRunResponse.ProtoReflect.Descriptor instead.
func (*ResumeRunResponse) Descriptor() ([]byte, []int) {
	return file_ancora_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeRunResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_ancora_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ancora_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_ancora_proto_rawDescGZIP(), []int{6}
}

func (x *StreamEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_ancora_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ancora_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_ancora_proto_rawDescGZIP(), []int{7}
}

func (x *EventResponse) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type DecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Decision      []byte                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_ancora_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ancora_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_ancora_proto_rawDescGZIP(), []int{8}
}

func (x *DecisionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *DecisionRequest) GetDecision() []byte {
	if x != nil {
		return x.Decision
	}
	return nil
}

var File_ancora_proto protoreflect.FileDescriptor

const file_ancora_proto_rawDesc = "" +
	"\n" +
	"\fancora.proto\x12\x06ancora\"0\n" +
	"\x0fStartRunRequest\x12\x1d\n" +
	"\n" +
	"agent_spec\x18\x01 \x01(\fR\tagentSpec\")\n" +
	"\x10StartRunResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"'\n" +
	"\x0ePollRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"'\n" +
	"\x0fPollRunResponse\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\"E\n" +
	"\x10ResumeRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\fR\bdecision\"+\n" +
	"\x11ResumeRunResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\",\n" +
	"\x13StreamEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"%\n" +
	"\rEventResponse\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\"D\n" +
	"\x0fDecisionRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\fR\bdecision2\xd5\x02\n" +
	"\n" +
	"RunService\x12=\n" +
	"\bStartRun\x12\x17.ancora.StartRunRequest\x1a\x18.ancora.StartRunResponse\x12:\n" +
	"\aPollRun\x12\x16.ancora.PollRunRequest\x1a\x17.ancora.PollRunResponse\x12@\n" +
	"\tResumeRun\x12\x18.ancora.ResumeRunRequest\x1a\x19.ancora.ResumeRunResponse\x12D\n" +
	"\fStreamEvents\x12\x1b.ancora.StreamEventsRequest\x1a\x15.ancora.EventResponse0\x01\x12D\n" +
	"\x0eDecisionStream\x12\x17.ancora.DecisionRequest\x1a\x15.ancora.EventResponse(\x010\x01B&Z$ancora.io/sdk/ancora/grpc;runserviceb\x06proto3"

var (
	file_ancora_proto_rawDescOnce sync.Once
	file_ancora_proto_rawDescData []byte
)

func file_ancora_proto_rawDescGZIP() []byte {
	file_ancora_proto_rawDescOnce.Do(func() {
		file_ancora_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ancora_proto_rawDesc), len(file_ancora_proto_rawDesc)))
	})
	return file_ancora_proto_rawDescData
}

var file_ancora_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ancora_proto_goTypes = []any{
	(*StartRunRequest)(nil),     // 0: ancora.StartRunRequest
	(*StartRunResponse)(nil),    // 1: ancora.StartRunResponse
	(*PollRunRequest)(nil),      // 2: ancora.PollRunRequest
	(*PollRunResponse)(nil),     // 3: ancora.PollRunResponse
	(*ResumeRunRequest)(nil),    // 4: ancora.ResumeRunRequest
	(*ResumeRunResponse)(nil),   // 5: ancora.ResumeRunResponse
	(*StreamEventsRequest)(nil), // 6: ancora.StreamEventsRequest
	(*EventResponse)(nil),       // 7: ancora.EventResponse
	(*DecisionRequest)(nil),     // 8: ancora.DecisionRequest
}
var file_ancora_proto_depIdxs = []int32{
	0, // 0: ancora.RunService.StartRun:input_type -> ancora.StartRunRequest
	2, // 1: ancora.RunService.PollRun:input_type -> ancora.PollRunRequest
	4, // 2: ancora.RunService.ResumeRun:input_type -> ancora.ResumeRunRequest
	6, // 3: ancora.RunService.StreamEvents:input_type -> ancora.StreamEventsRequest
	8, // 4: ancora.RunService.DecisionStream:input_type -> ancora.DecisionRequest
	1, // 5: ancora.RunService.StartRun:output_type -> ancora.StartRunResponse
	3, // 6: ancora.RunService.PollRun:output_type -> ancora.PollRunResponse
	5, // 7: ancora.RunService.ResumeRun:output_type -> ancora.ResumeRunResponse
	7, // 8: ancora.RunService.StreamEvents:output_type -> ancora.EventResponse
	7, // 9: ancora.RunService.DecisionStream:output_type -> ancora.EventResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ancora_proto_init() }
func file_ancora_proto_init() {
	if File_ancora_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ancora_proto_rawDesc), len(file_ancora_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ancora_proto_goTypes,
		DependencyIndexes: file_ancora_proto_depIdxs,
		MessageInfos:      file_ancora_proto_msgTypes,
	}.Build()
	File_ancora_proto = out.File
	file_ancora_proto_goTypes = nil
	file_ancora_proto_depIdxs = nil
}
