// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: ancora.proto

package runservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunService_StartRun_FullMethodName       = "/ancora.RunService/StartRun"
	RunService_PollRun_FullMethodName        = "/ancora.RunService/PollRun"
	RunService_ResumeRun_FullMethodName      = "/ancora.RunService/ResumeRun"
	RunService_StreamEvents_FullMethodName   = "/ancora.RunService/StreamEvents"
	RunService_DecisionStream_FullMethodName = "/ancora.RunService/DecisionStream"
)

// RunServiceClient is the client API for RunService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunServiceClient interface {
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error)
	PollRun(ctx context.Context, in *PollRunRequest, opts ...grpc.CallOption) (*PollRunResponse, error)
	ResumeRun(ctx context.Context, in *ResumeRunRequest, opts ...grpc.CallOption) (*ResumeRunResponse, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error)
	DecisionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DecisionRequest, EventResponse], error)
}

type runServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunServiceClient(cc grpc.ClientConnInterface) RunServiceClient {
	return &runServiceClient{cc}
}

func (c *runServiceClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRunResponse)
	err := c.cc.Invoke(ctx, RunService_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) PollRun(ctx context.Context, in *PollRunRequest, opts ...grpc.CallOption) (*PollRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollRunResponse)
	err := c.cc.Invoke(ctx, RunService_PollRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) ResumeRun(ctx context.Context, in *ResumeRunRequest, opts ...grpc.CallOption) (*ResumeRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeRunResponse)
	err := c.cc.Invoke(ctx, RunService_ResumeRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunService_ServiceDesc.Streams[0], RunService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, EventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunService_StreamEventsClient = grpc.ServerStreamingClient[EventResponse]

func (c *runServiceClient) DecisionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DecisionRequest, EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunService_ServiceDesc.Streams[1], RunService_DecisionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DecisionRequest, EventResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunService_DecisionStreamClient = grpc.BidiStreamingClient[DecisionRequest, EventResponse]

// RunServiceServer is the server API for RunService service.
// All implementations must embed UnimplementedRunServiceServer
// for forward compatibility.
type RunServiceServer interface {
	StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error)
	PollRun(context.Context, *PollRunRequest) (*PollRunResponse, error)
	ResumeRun(context.Context, *ResumeRunRequest) (*ResumeRunResponse, error)
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[EventResponse]) error
	DecisionStream(grpc.BidiStreamingServer[DecisionRequest, EventResponse]) error
	mustEmbedUnimplementedRunServiceServer()
}

// UnimplementedRunServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunServiceServer struct{}

func (UnimplementedRunServiceServer) StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedRunServiceServer) PollRun(context.Context, *PollRunRequest) (*PollRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollRun not implemented")
}
func (UnimplementedRunServiceServer) ResumeRun(context.Context, *ResumeRunRequest) (*ResumeRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeRun not implemented")
}
func (UnimplementedRunServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[EventResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedRunServiceServer) DecisionStream(grpc.BidiStreamingServer[DecisionRequest, EventResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DecisionStream not implemented")
}
func (UnimplementedRunServiceServer) mustEmbedUnimplementedRunServiceServer() {}
func (UnimplementedRunServiceServer) testEmbeddedByValue()                    {}

// UnsafeRunServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunServiceServer will
// result in compilation errors.
type UnsafeRunServiceServer interface {
	mustEmbedUnimplementedRunServiceServer()
}

func RegisterRunServiceServer(s grpc.ServiceRegistrar, srv RunServiceServer) {
	// If the following call pancis, it indicates UnimplementedRunServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunService_ServiceDesc, srv)
}

func _RunService_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunService_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_PollRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).PollRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunService_PollRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).PollRun(ctx, req.(*PollRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_ResumeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).ResumeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunService_ResumeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).ResumeRun(ctx, req.(*ResumeRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunService_StreamEventsServer = grpc.ServerStreamingServer[EventResponse]

func _RunService_DecisionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunServiceServer).DecisionStream(&grpc.GenericServerStream[DecisionRequest, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunService_DecisionStreamServer = grpc.BidiStreamingServer[DecisionRequest, EventResponse]

// RunService_ServiceDesc is the grpc.ServiceDesc for RunService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ancora.RunService",
	HandlerType: (*RunServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _RunService_StartRun_Handler,
		},
		{
			MethodName: "PollRun",
			Handler:    _RunService_PollRun_Handler,
		},
		{
			MethodName: "ResumeRun",
			Handler:    _RunService_ResumeRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _RunService_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DecisionStream",
			Handler:       _RunService_DecisionStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ancora.proto",
}
